In [2]:
import polars as pl
import os

In [3]:
import numpy as np
import math

In [11]:
os.getcwd()

'C:\\Users\\carlo\\OneDrive\\Documentos\\Carlos_universidad\\oct_semestre\\proyectosMatematicas\\COIL\\notebooks'

Las papas están con los cereales y añadí los  frutos secos a grasas
La mayoría de galletas están s/i en azúcar totales :/

In [11]:
df_1=pl.read_excel("../data/INTA.xlsx",sheet_id=1)

In [19]:
pl.read_excel("../data/INTA.xlsx",sheet_id=3)

shape: (93, 10)
┌─────────────┬─────────────┬─────────┬──────┬───┬────────────┬──────────┬────────────┬────────────┐
│ Grupo de    ┆ Alimento    ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA(poli) ┆ SAT (gr) ┆ SODIO mg   ┆ AZUCAR AÑA │
│ alimento    ┆ ---         ┆ ---     ┆ ---  ┆   ┆ ---        ┆ ---      ┆ pasar a gr ┆ DIDA(gr)   │
│ ---         ┆ str         ┆ i64     ┆ i64  ┆   ┆ str        ┆ f64      ┆ ---        ┆ ---        │
│ str         ┆             ┆         ┆      ┆   ┆            ┆          ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════════╪══════╪═══╪════════════╪══════════╪════════════╪════════════╡
│ VERDURAS    ┆ Acelga      ┆ 100     ┆ 27   ┆ … ┆ 0          ┆ 0.0      ┆ 0.0        ┆ null       │
│ VERDURAS    ┆ Achicoria   ┆ 100     ┆ 23   ┆ … ┆ 0.13       ┆ 0.07     ┆ 45.0       ┆ null       │
│ VERDURAS    ┆ Ajo         ┆ 100     ┆ 149  ┆ … ┆ 0.25       ┆ 0.09     ┆ 17.0       ┆ null       │
│ VERDURAS    ┆ Alcachofa   ┆ 100     ┆ 53   ┆ … ┆ 0.15       ┆ 0.08     ┆ 60.0       ┆ null       │
│ VERDURAS    ┆ Alfafa      ┆ 100     ┆ 23   ┆ … ┆ 0.41       ┆ 0.07     ┆ 6.0        ┆ null       │
│             ┆ brotes      ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ …           ┆ …           ┆ …       ┆ …    ┆ … ┆ …          ┆ …        ┆ …          ┆ …          │
│ null        ┆ Nectar      ┆ 100     ┆ 15   ┆ … ┆ 0          ┆ 0.0      ┆ 8.0        ┆ 0.0        │
│             ┆ durazco     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│             ┆ light       ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar      ┆ 100     ┆ 41   ┆ … ┆ 0          ┆ 0.0      ┆ 7.0        ┆ 8.6        │
│             ┆ manzana     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar      ┆ 100     ┆ 41   ┆ … ┆ 0          ┆ 0.0      ┆ 7.0        ┆ 8.0        │
│             ┆ naranja     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar      ┆ 100     ┆ 20   ┆ … ┆ 0          ┆ 0.0      ┆ 7.0        ┆ 3.1        │
│             ┆ naranja     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│             ┆ light       ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar uva  ┆ 100     ┆ 9    ┆ … ┆ 0          ┆ 0.0      ┆ 17.0       ┆ 1.7        │
│             ┆ light       ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
└─────────────┴─────────────┴─────────┴──────┴───┴────────────┴──────────┴────────────┴────────────┘

In [12]:
df_1

shape: (25, 10)
┌────────────┬──────────────────┬─────────┬──────┬───┬───────────┬──────────┬────────────┬─────────┐
│ Grupo de   ┆ Alimento         ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA (gr) ┆ SAT (gr) ┆ SODIO (gr) ┆ AZUCAR  │
│ alimento   ┆ ---              ┆ ---     ┆ ---  ┆   ┆ ---       ┆ ---      ┆ ---        ┆ AÑADIDA │
│ ---        ┆ str              ┆ i64     ┆ i64  ┆   ┆ f64       ┆ f64      ┆ f64        ┆ (gr)    │
│ str        ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆ ---     │
│            ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆ str     │
╞════════════╪══════════════════╪═════════╪══════╪═══╪═══════════╪══════════╪════════════╪═════════╡
│ Leche y    ┆ Leche entera     ┆ 100     ┆ 64   ┆ … ┆ 0.14      ┆ 2.28     ┆ 0.049      ┆ null    │
│ derivados  ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ Leche entera con ┆ 100     ┆ 80   ┆ … ┆ 0.15      ┆ 1.84     ┆ 0.0596     ┆ null    │
│ derivados  ┆ sabor            ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ leche            ┆ 100     ┆ 42   ┆ … ┆ 0.05      ┆ 1.0      ┆ 0.06       ┆ null    │
│ derivados  ┆ semidescremada   ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ leche            ┆ 100     ┆ 76   ┆ … ┆ 0.09      ┆ 1.18     ┆ 0.066      ┆ null    │
│ derivados  ┆ semidescremada   ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│            ┆ con sabor        ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ leche descremada ┆ 100     ┆ 42   ┆ … ┆ 0.04      ┆ 0.63     ┆ 0.044      ┆ null    │
│ derivados  ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ …          ┆ …                ┆ …       ┆ …    ┆ … ┆ …         ┆ …        ┆ …          ┆ …       │
│ Pescados y ┆ camaron          ┆ 100     ┆ 85   ┆ … ┆ 0.15      ┆ 0.1      ┆ 0.119      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ atun en agua     ┆ 100     ┆ 131  ┆ … ┆ 0.13      ┆ 0.16     ┆ 0.356      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ jurel            ┆ 100     ┆ 105  ┆ … ┆ 0.46      ┆ 0.36     ┆ 0.158      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ merluza          ┆ 100     ┆ 89   ┆ … ┆ 0.33      ┆ 0.18     ┆ 0.053      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ salmón           ┆ 100     ┆ 146  ┆ … ┆ 1.99      ┆ 1.26     ┆ 0.046      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
└────────────┴──────────────────┴─────────┴──────┴───┴───────────┴──────────┴────────────┴─────────┘

In [148]:
dfl=[]
for i in range(4):
    dfl.append(pl.read_excel("../data/INTA.xlsx",sheet_id=1+i))

In [28]:
dfl[0]

shape: (25, 10)
┌────────────┬──────────────────┬─────────┬──────┬───┬───────────┬──────────┬────────────┬─────────┐
│ Grupo de   ┆ Alimento         ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA (gr) ┆ SAT (gr) ┆ SODIO (gr) ┆ AZUCAR  │
│ alimento   ┆ ---              ┆ ---     ┆ ---  ┆   ┆ ---       ┆ ---      ┆ ---        ┆ AÑADIDA │
│ ---        ┆ str              ┆ i64     ┆ i64  ┆   ┆ f64       ┆ f64      ┆ f64        ┆ (gr)    │
│ str        ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆ ---     │
│            ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆ str     │
╞════════════╪══════════════════╪═════════╪══════╪═══╪═══════════╪══════════╪════════════╪═════════╡
│ Leche y    ┆ Leche entera     ┆ 100     ┆ 64   ┆ … ┆ 0.14      ┆ 2.28     ┆ 0.049      ┆ null    │
│ derivados  ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ Leche entera con ┆ 100     ┆ 80   ┆ … ┆ 0.15      ┆ 1.84     ┆ 0.0596     ┆ null    │
│ derivados  ┆ sabor            ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ leche            ┆ 100     ┆ 42   ┆ … ┆ 0.05      ┆ 1.0      ┆ 0.06       ┆ null    │
│ derivados  ┆ semidescremada   ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ leche            ┆ 100     ┆ 76   ┆ … ┆ 0.09      ┆ 1.18     ┆ 0.066      ┆ null    │
│ derivados  ┆ semidescremada   ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│            ┆ con sabor        ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Leche y    ┆ leche descremada ┆ 100     ┆ 42   ┆ … ┆ 0.04      ┆ 0.63     ┆ 0.044      ┆ null    │
│ derivados  ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ …          ┆ …                ┆ …       ┆ …    ┆ … ┆ …         ┆ …        ┆ …          ┆ …       │
│ Pescados y ┆ camaron          ┆ 100     ┆ 85   ┆ … ┆ 0.15      ┆ 0.1      ┆ 0.119      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ atun en agua     ┆ 100     ┆ 131  ┆ … ┆ 0.13      ┆ 0.16     ┆ 0.356      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ jurel            ┆ 100     ┆ 105  ┆ … ┆ 0.46      ┆ 0.36     ┆ 0.158      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ merluza          ┆ 100     ┆ 89   ┆ … ┆ 0.33      ┆ 0.18     ┆ 0.053      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
│ Pescados y ┆ salmón           ┆ 100     ┆ 146  ┆ … ┆ 1.99      ┆ 1.26     ┆ 0.046      ┆ null    │
│ mariscos   ┆                  ┆         ┆      ┆   ┆           ┆          ┆            ┆         │
└────────────┴──────────────────┴─────────┴──────┴───┴───────────┴──────────┴────────────┴─────────┘

In [31]:
dfl[0][dfl[0].columns[0]].drop_nulls().unique()

shape: (4,)
Series: 'Grupo de alimento' [str]
[
	"Leche y deriva…
	"Pescados y mar…
	"Huevo"
	"Carnes y visce…
]

In [39]:
a=[]
for i in range(len(dfl)):
    a.append(dfl[i].columns)
    for i in a:
        print(i)

['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)', 'PUFA (gr)', 'SAT (gr)', 'SODIO (gr)', 'AZUCAR AÑADIDA (gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)', 'PUFA (gr)', 'SAT (gr)', 'SODIO (gr)', 'AZUCAR AÑADIDA (gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA', 'PUFA', 'SAT', 'SODIO (gr)', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)', 'PUFA (gr)', 'SAT (gr)', 'SODIO (gr)', 'AZUCAR AÑADIDA (gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA', 'PUFA', 'SAT', 'SODIO (gr)', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)(mono', 'PUFA(poli)', 'SAT (gr)', 'SODIO mg pasar a gr', 'AZUCAR AÑADIDA(gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)', 'PUFA (gr)', 'SAT (gr)', 'SODIO (gr)', 'AZUCAR AÑADIDA (gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA', 'PUFA', 'SAT', 'SODIO (gr)', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)(mono', 'PUFA(poli)', 'SAT (gr)', 'SODIO mg pasar a gr', 'AZUCAR AÑADIDA(gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']

### Esto nos dice que las dos primeras paginas tienen las mismas columnas por lo que podemos concatenarlas de manera vertical

In [40]:
a

[['Grupo de alimento',
  'Alimento',
  'Gramaje',
  'KCAL',
  'PROT (gr)',
  'MUFA (gr)',
  'PUFA (gr)',
  'SAT (gr)',
  'SODIO (gr)',
  'AZUCAR AÑADIDA (gr)'],
 ['Grupo de alimento',
  'Alimento',
  'Gramaje',
  'KCAL',
  'PROT (gr)',
  'MUFA',
  'PUFA',
  'SAT',
  'SODIO (gr)',
  'AZUCAR AÑADIDA'],
 ['Grupo de alimento',
  'Alimento',
  'Gramaje',
  'KCAL',
  'PROT (gr)',
  'MUFA (gr)(mono',
  'PUFA(poli)',
  'SAT (gr)',
  'SODIO mg pasar a gr',
  'AZUCAR AÑADIDA(gr)'],
 ['Grupo de alimento',
  'Alimento',
  'Gramaje',
  'KCAL',
  'PROT (gr)',
  'MUFA',
  'PUFA',
  'SAT',
  'SODIO',
  'AZUCAR AÑADIDA']]

In [43]:
for i in range(len(dfl)):
    print(dfl[i].columns)

['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)', 'PUFA (gr)', 'SAT (gr)', 'SODIO (gr)', 'AZUCAR AÑADIDA (gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA', 'PUFA', 'SAT', 'SODIO (gr)', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA (gr)(mono', 'PUFA(poli)', 'SAT (gr)', 'SODIO mg pasar a gr', 'AZUCAR AÑADIDA(gr)']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT (gr)', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']

In [44]:
dfl[2]

shape: (93, 10)
┌─────────────┬─────────────┬─────────┬──────┬───┬────────────┬──────────┬────────────┬────────────┐
│ Grupo de    ┆ Alimento    ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA(poli) ┆ SAT (gr) ┆ SODIO mg   ┆ AZUCAR AÑA │
│ alimento    ┆ ---         ┆ ---     ┆ ---  ┆   ┆ ---        ┆ ---      ┆ pasar a gr ┆ DIDA(gr)   │
│ ---         ┆ str         ┆ i64     ┆ i64  ┆   ┆ str        ┆ f64      ┆ ---        ┆ ---        │
│ str         ┆             ┆         ┆      ┆   ┆            ┆          ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════════╪══════╪═══╪════════════╪══════════╪════════════╪════════════╡
│ VERDURAS    ┆ Acelga      ┆ 100     ┆ 27   ┆ … ┆ 0          ┆ 0.0      ┆ 0.0        ┆ null       │
│ VERDURAS    ┆ Achicoria   ┆ 100     ┆ 23   ┆ … ┆ 0.13       ┆ 0.07     ┆ 45.0       ┆ null       │
│ VERDURAS    ┆ Ajo         ┆ 100     ┆ 149  ┆ … ┆ 0.25       ┆ 0.09     ┆ 17.0       ┆ null       │
│ VERDURAS    ┆ Alcachofa   ┆ 100     ┆ 53   ┆ … ┆ 0.15       ┆ 0.08     ┆ 60.0       ┆ null       │
│ VERDURAS    ┆ Alfafa      ┆ 100     ┆ 23   ┆ … ┆ 0.41       ┆ 0.07     ┆ 6.0        ┆ null       │
│             ┆ brotes      ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ …           ┆ …           ┆ …       ┆ …    ┆ … ┆ …          ┆ …        ┆ …          ┆ …          │
│ null        ┆ Nectar      ┆ 100     ┆ 15   ┆ … ┆ 0          ┆ 0.0      ┆ 8.0        ┆ 0.0        │
│             ┆ durazco     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│             ┆ light       ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar      ┆ 100     ┆ 41   ┆ … ┆ 0          ┆ 0.0      ┆ 7.0        ┆ 8.6        │
│             ┆ manzana     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar      ┆ 100     ┆ 41   ┆ … ┆ 0          ┆ 0.0      ┆ 7.0        ┆ 8.0        │
│             ┆ naranja     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar      ┆ 100     ┆ 20   ┆ … ┆ 0          ┆ 0.0      ┆ 7.0        ┆ 3.1        │
│             ┆ naranja     ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│             ┆ light       ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
│ null        ┆ Nectar uva  ┆ 100     ┆ 9    ┆ … ┆ 0          ┆ 0.0      ┆ 17.0       ┆ 1.7        │
│             ┆ light       ┆         ┆      ┆   ┆            ┆          ┆            ┆            │
└─────────────┴─────────────┴─────────┴──────┴───┴────────────┴──────────┴────────────┴────────────┘

In [149]:
dfl[2] = dfl[2].select(
    *[ # 1. Desempaqueta la lista
        (pl.col('SODIO mg pasar a gr') * (1/1000)).alias('SODIO')
        if col == 'SODIO mg pasar a gr' # 3. Si la columna es esa, la reemplazas
        else pl.col(col) # 4. Si no, la dejas igual
        for col in dfl[2].columns # 2. Aquí se define col: recorre cada nombre de columna
    ]
)

In [150]:
dfl[2].columns

['Grupo de alimento',
 'Alimento',
 'Gramaje',
 'KCAL',
 'PROT (gr)',
 'MUFA (gr)(mono',
 'PUFA(poli)',
 'SAT (gr)',
 'SODIO',
 'AZUCAR AÑADIDA(gr)']

In [84]:
len(dfl[2].columns)

10

In [151]:
dfl[2]['SODIO']

shape: (93,)
Series: 'SODIO' [f64]
[
	0.0
	0.045
	0.017
	0.06
	0.006
	0.08
	0.001
	0.041
	0.078
	0.024
	0.004
	0.016
	…
	0.001
	0.001
	0.014
	0.001
	0.001
	0.008
	0.009
	0.009
	0.008
	0.007
	0.007
	0.007
	0.017
]

In [152]:
nombres_de_columnas_ideales=['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']
print(len(nombres_de_columnas_ideales))

10

In [72]:
#dfl[2]=dfl[2].drop('SODIO')
#print(len(dfl[2].columns))

In [153]:
for i in range(len(dfl)):
    dfl[i].columns=nombres_de_columnas_ideales

In [154]:
print(dfl[3].columns)

['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']

In [155]:
for i in range(len(dfl)):
    print(dfl[i].columns)

['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']
['Grupo de alimento', 'Alimento', 'Gramaje', 'KCAL', 'PROT', 'MUFA', 'PUFA', 'SAT', 'SODIO', 'AZUCAR AÑADIDA']

shape: (50, 10)
┌───────────┬───────────────────────┬─────────┬──────┬───┬───────┬───────┬────────┬────────────────┐
│ Grupo de  ┆ Alimento              ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA  ┆ SAT   ┆ SODIO  ┆ AZUCAR AÑADIDA │
│ alimento  ┆ ---                   ┆ ---     ┆ ---  ┆   ┆ ---   ┆ ---   ┆ ---    ┆ ---            │
│ ---       ┆ str                   ┆ i64     ┆ i64  ┆   ┆ f64   ┆ f64   ┆ f64    ┆ f64            │
│ str       ┆                       ┆         ┆      ┆   ┆       ┆       ┆        ┆                │
╞═══════════╪═══════════════════════╪═════════╪══════╪═══╪═══════╪═══════╪════════╪════════════════╡
│ Legumbres ┆ Arvejas               ┆ 100     ┆ 81   ┆ … ┆ 0.19  ┆ 0.07  ┆ 0.005  ┆ null           │
│ Legumbres ┆ Garbanzo              ┆ 100     ┆ 163  ┆ … ┆ 1.16  ┆ 0.27  ┆ 0.007  ┆ null           │
│ Legumbres ┆ Haba                  ┆ 100     ┆ 72   ┆ … ┆ 0.331 ┆ 0.14  ┆ 0.05   ┆ null           │
│ Legumbres ┆ Lenteja               ┆ 100     ┆ 116  ┆ … ┆ 0.06  ┆ 0.4   ┆ 0.002  ┆ null           │
│ Legumbres ┆ Poroto                ┆ 100     ┆ 139  ┆ … ┆ 0.15  ┆ 0.09  ┆ 0.006  ┆ null           │
│ …         ┆ …                     ┆ …       ┆ …    ┆ … ┆ …     ┆ …     ┆ …      ┆ …              │
│ Grasas y  ┆ Aceite de maravilla   ┆ 100     ┆ 884  ┆ … ┆ 65.7  ┆ 10.3  ┆ 0.0    ┆ null           │
│ Aceites   ┆                       ┆         ┆      ┆   ┆       ┆       ┆        ┆                │
│ Grasas y  ┆ Aceite de oliva       ┆ 100     ┆ 884  ┆ … ┆ 10.52 ┆ 13.81 ┆ 0.002  ┆ null           │
│ Aceites   ┆                       ┆         ┆      ┆   ┆       ┆       ┆        ┆                │
│ Grasas y  ┆ Aceite de oliva extra ┆ 100     ┆ 887  ┆ … ┆ 6.59  ┆ 12.13 ┆ 0.0003 ┆ null           │
│ Aceites   ┆ virgen                ┆         ┆      ┆   ┆       ┆       ┆        ┆                │
│ Grasas y  ┆ Aceite de palma       ┆ 100     ┆ 884  ┆ … ┆ 9.3   ┆ 49.3  ┆ 0.0    ┆ null           │
│ Aceites   ┆                       ┆         ┆      ┆   ┆       ┆       ┆        ┆                │
│ Grasas y  ┆ Aceite de soja        ┆ 100     ┆ 897  ┆ … ┆ 57.8  ┆ 14.7  ┆ 0.0    ┆ null           │
│ Aceites   ┆                       ┆         ┆      ┆   ┆       ┆       ┆        ┆                │
└───────────┴───────────────────────┴─────────┴──────┴───┴───────┴───────┴────────┴────────────────┘

In [156]:
ultim=pl.concat([dfl[0],dfl[1],dfl[2],dfl[3]],how="vertical_relaxed")

In [157]:
dfl[1].head()

shape: (5, 10)
┌───────────────────┬───────────┬─────────┬──────┬───┬───────┬──────┬───────┬────────────────┐
│ Grupo de alimento ┆ Alimento  ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA  ┆ SAT  ┆ SODIO ┆ AZUCAR AÑADIDA │
│ ---               ┆ ---       ┆ ---     ┆ ---  ┆   ┆ ---   ┆ ---  ┆ ---   ┆ ---            │
│ str               ┆ str       ┆ i64     ┆ i64  ┆   ┆ f64   ┆ f64  ┆ f64   ┆ f64            │
╞═══════════════════╪═══════════╪═════════╪══════╪═══╪═══════╪══════╪═══════╪════════════════╡
│ Legumbres         ┆ Arvejas   ┆ 100     ┆ 81   ┆ … ┆ 0.19  ┆ 0.07 ┆ 0.005 ┆ null           │
│ Legumbres         ┆ Garbanzo  ┆ 100     ┆ 163  ┆ … ┆ 1.16  ┆ 0.27 ┆ 0.007 ┆ null           │
│ Legumbres         ┆ Haba      ┆ 100     ┆ 72   ┆ … ┆ 0.331 ┆ 0.14 ┆ 0.05  ┆ null           │
│ Legumbres         ┆ Lenteja   ┆ 100     ┆ 116  ┆ … ┆ 0.06  ┆ 0.4  ┆ 0.002 ┆ null           │
│ Legumbres         ┆ Poroto    ┆ 100     ┆ 139  ┆ … ┆ 0.15  ┆ 0.09 ┆ 0.006 ┆ null           │
└───────────────────┴───────────┴─────────┴──────┴───┴───────┴──────┴───────┴────────────────┘

In [158]:
ultim[24:]

shape: (179, 10)
┌────────────┬────────────────────────┬─────────┬──────┬───┬───────┬──────┬───────┬────────────────┐
│ Grupo de   ┆ Alimento               ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA  ┆ SAT  ┆ SODIO ┆ AZUCAR AÑADIDA │
│ alimento   ┆ ---                    ┆ ---     ┆ ---  ┆   ┆ ---   ┆ ---  ┆ ---   ┆ ---            │
│ ---        ┆ str                    ┆ i64     ┆ i64  ┆   ┆ str   ┆ str  ┆ str   ┆ str            │
│ str        ┆                        ┆         ┆      ┆   ┆       ┆      ┆       ┆                │
╞════════════╪════════════════════════╪═════════╪══════╪═══╪═══════╪══════╪═══════╪════════════════╡
│ Pescados y ┆ salmón                 ┆ 100     ┆ 146  ┆ … ┆ 1.99  ┆ 1.26 ┆ 0.046 ┆ null           │
│ mariscos   ┆                        ┆         ┆      ┆   ┆       ┆      ┆       ┆                │
│ Legumbres  ┆ Arvejas                ┆ 100     ┆ 81   ┆ … ┆ 0.19  ┆ 0.07 ┆ 0.005 ┆ null           │
│ Legumbres  ┆ Garbanzo               ┆ 100     ┆ 163  ┆ … ┆ 1.16  ┆ 0.27 ┆ 0.007 ┆ null           │
│ Legumbres  ┆ Haba                   ┆ 100     ┆ 72   ┆ … ┆ 0.331 ┆ 0.14 ┆ 0.05  ┆ null           │
│ Legumbres  ┆ Lenteja                ┆ 100     ┆ 116  ┆ … ┆ 0.06  ┆ 0.4  ┆ 0.002 ┆ null           │
│ …          ┆ …                      ┆ …       ┆ …    ┆ … ┆ …     ┆ …    ┆ …     ┆ …              │
│ Salsas     ┆ Salsa de tomates (2)   ┆ 100     ┆ 47   ┆ … ┆ s/i   ┆ s/i  ┆ 0.356 ┆ null           │
│ Salsas     ┆ Salsa de tomates con   ┆ 100     ┆ 42   ┆ … ┆ 0.08  ┆ 0.03 ┆ 0.551 ┆ null           │
│            ┆ cebolla                ┆         ┆      ┆   ┆       ┆      ┆       ┆                │
│ Salsas     ┆ Salsa tártara          ┆ 100     ┆ 211  ┆ … ┆ 9.04  ┆ 3.33 ┆ 0.667 ┆ null           │
│ Salsas     ┆ Salsa teriyaki         ┆ 100     ┆ 89   ┆ … ┆ 0     ┆ 0    ┆ 3.833 ┆ null           │
│ Salsas     ┆ Salsa verde            ┆ 100     ┆ 38   ┆ … ┆ 0     ┆ 0    ┆ 0.6   ┆ null           │
└────────────┴────────────────────────┴─────────┴──────┴───┴───────┴──────┴───────┴────────────────┘

In [159]:
ultim.write_parquet('../datos_correctos')

In [160]:
ultim[168:203]==dfl[3]

shape: (35, 10)
┌───────────────────┬──────────┬─────────┬──────┬───┬──────┬──────┬───────┬────────────────┐
│ Grupo de alimento ┆ Alimento ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA ┆ SAT  ┆ SODIO ┆ AZUCAR AÑADIDA │
│ ---               ┆ ---      ┆ ---     ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---   ┆ ---            │
│ bool              ┆ bool     ┆ bool    ┆ bool ┆   ┆ bool ┆ bool ┆ bool  ┆ bool           │
╞═══════════════════╪══════════╪═════════╪══════╪═══╪══════╪══════╪═══════╪════════════════╡
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ …                 ┆ …        ┆ …       ┆ …    ┆ … ┆ …    ┆ …    ┆ …     ┆ …              │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
│ true              ┆ true     ┆ true    ┆ true ┆ … ┆ true ┆ true ┆ true  ┆ null           │
└───────────────────┴──────────┴─────────┴──────┴───┴──────┴──────┴───────┴────────────────┘

In [115]:
dfl[3][0:10].remove(pl.col(dfl[3].columns)=="s/i")

AttributeError: 'DataFrame' object has no attribute 'remove'

In [161]:
np.array(dfl[0].shape[0])+np.array(dfl[1].shape[0]+np.array(dfl[2].shape[0]))

168

In [164]:
dlf.remove(pl.col("bar")>5)

NameError: name 'dlf' is not defined

In [135]:
print(ultim['Grupo de alimento'].unique())

shape: (16,)
Series: 'Grupo de alimento' [str]
[
	null
	"    FRUTAS ENT…
	"Carnes y visce…
	"   JUGOS Y NEC…
	"Bebidas "
	"Pescados y mar…
	"    AZUCARES Y…
	"Legumbres"
	"         VERDU…
	"Salsas"
	"Bebidas alcohó…
	"Productos sala…
	"Leche y deriva…
	"Cereales"
	"Grasas y Aceit…
	"Huevo"
]

In [163]:
print(len(list(ultim['Grupo de alimento'].unique())))

15

In [139]:
ultim

shape: (203, 10)
┌───────────┬─────────────────────────┬─────────┬──────┬───┬──────┬──────┬────────┬────────────────┐
│ Grupo de  ┆ Alimento                ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA ┆ SAT  ┆ SODIO  ┆ AZUCAR AÑADIDA │
│ alimento  ┆ ---                     ┆ ---     ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---    ┆ ---            │
│ ---       ┆ str                     ┆ i64     ┆ i64  ┆   ┆ str  ┆ str  ┆ str    ┆ str            │
│ str       ┆                         ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
╞═══════════╪═════════════════════════╪═════════╪══════╪═══╪══════╪══════╪════════╪════════════════╡
│ Leche y   ┆ Leche entera            ┆ 100     ┆ 64   ┆ … ┆ 0.14 ┆ 2.28 ┆ 0.049  ┆ null           │
│ derivados ┆                         ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
│ Leche y   ┆ Leche entera con sabor  ┆ 100     ┆ 80   ┆ … ┆ 0.15 ┆ 1.84 ┆ 0.0596 ┆ null           │
│ derivados ┆                         ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
│ Leche y   ┆ leche semidescremada    ┆ 100     ┆ 42   ┆ … ┆ 0.05 ┆ 1.0  ┆ 0.06   ┆ null           │
│ derivados ┆                         ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
│ Leche y   ┆ leche semidescremada    ┆ 100     ┆ 76   ┆ … ┆ 0.09 ┆ 1.18 ┆ 0.066  ┆ null           │
│ derivados ┆ con sabor               ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
│ Leche y   ┆ leche descremada        ┆ 100     ┆ 42   ┆ … ┆ 0.04 ┆ 0.63 ┆ 0.044  ┆ null           │
│ derivados ┆                         ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
│ …         ┆ …                       ┆ …       ┆ …    ┆ … ┆ …    ┆ …    ┆ …      ┆ …              │
│ Salsas    ┆ Salsa de tomates (2)    ┆ 100     ┆ 47   ┆ … ┆ s/i  ┆ s/i  ┆ 0.356  ┆ null           │
│ Salsas    ┆ Salsa de tomates con    ┆ 100     ┆ 42   ┆ … ┆ 0.08 ┆ 0.03 ┆ 0.551  ┆ null           │
│           ┆ cebolla                 ┆         ┆      ┆   ┆      ┆      ┆        ┆                │
│ Salsas    ┆ Salsa tártara           ┆ 100     ┆ 211  ┆ … ┆ 9.04 ┆ 3.33 ┆ 0.667  ┆ null           │
│ Salsas    ┆ Salsa teriyaki          ┆ 100     ┆ 89   ┆ … ┆ 0    ┆ 0    ┆ 3.833  ┆ null           │
│ Salsas    ┆ Salsa verde             ┆ 100     ┆ 38   ┆ … ┆ 0    ┆ 0    ┆ 0.6    ┆ null           │
└───────────┴─────────────────────────┴─────────┴──────┴───┴──────┴──────┴────────┴────────────────┘

In [146]:
ultim['Grupo de alimento'=='Leche y derivados']

shape: (1, 10)
┌───────────────────┬──────────────┬─────────┬──────┬───┬──────┬──────┬───────┬────────────────┐
│ Grupo de alimento ┆ Alimento     ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA ┆ SAT  ┆ SODIO ┆ AZUCAR AÑADIDA │
│ ---               ┆ ---          ┆ ---     ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---   ┆ ---            │
│ str               ┆ str          ┆ i64     ┆ i64  ┆   ┆ str  ┆ str  ┆ str   ┆ str            │
╞═══════════════════╪══════════════╪═════════╪══════╪═══╪══════╪══════╪═══════╪════════════════╡
│ Leche y derivados ┆ Leche entera ┆ 100     ┆ 64   ┆ … ┆ 0.14 ┆ 2.28 ┆ 0.049 ┆ null           │
└───────────────────┴──────────────┴─────────┴──────┴───┴──────┴──────┴───────┴────────────────┘

In [147]:
dfl[3]

shape: (35, 10)
┌──────────┬──────────────────────┬─────────┬──────┬───┬──────┬──────┬───────┬────────────────┐
│ Grupo de ┆ Alimento             ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA ┆ SAT  ┆ SODIO ┆ AZUCAR AÑADIDA │
│ alimento ┆ ---                  ┆ ---     ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---   ┆ ---            │
│ ---      ┆ str                  ┆ i64     ┆ i64  ┆   ┆ str  ┆ str  ┆ str   ┆ str            │
│ str      ┆                      ┆         ┆      ┆   ┆      ┆      ┆       ┆                │
╞══════════╪══════════════════════╪═════════╪══════╪═══╪══════╪══════╪═══════╪════════════════╡
│ Bebidas  ┆ Agua tónica          ┆ 100     ┆ 34   ┆ … ┆ 0    ┆ 0    ┆ 0.012 ┆ null           │
│ Bebidas  ┆ Agua tónica          ┆ 100     ┆ 0    ┆ … ┆ s/i  ┆ s/i  ┆ s/i   ┆ null           │
│ Bebidas  ┆ Agua tónica          ┆ 100     ┆ 42   ┆ … ┆ 0    ┆ 0    ┆ 0.003 ┆ null           │
│ Bebidas  ┆ Agua tónica          ┆ 100     ┆ 43   ┆ … ┆ 0    ┆ 0    ┆ 0.039 ┆ null           │
│ Bebidas  ┆ Agua tónica          ┆ 100     ┆ 41   ┆ … ┆ 0    ┆ 0    ┆ 0.01  ┆ null           │
│ …        ┆ …                    ┆ …       ┆ …    ┆ … ┆ …    ┆ …    ┆ …     ┆ …              │
│ Salsas   ┆ Salsa de tomates (2) ┆ 100     ┆ 47   ┆ … ┆ s/i  ┆ s/i  ┆ 0.356 ┆ null           │
│ Salsas   ┆ Salsa de tomates con ┆ 100     ┆ 42   ┆ … ┆ 0.08 ┆ 0.03 ┆ 0.551 ┆ null           │
│          ┆ cebolla              ┆         ┆      ┆   ┆      ┆      ┆       ┆                │
│ Salsas   ┆ Salsa tártara        ┆ 100     ┆ 211  ┆ … ┆ 9.04 ┆ 3.33 ┆ 0.667 ┆ null           │
│ Salsas   ┆ Salsa teriyaki       ┆ 100     ┆ 89   ┆ … ┆ 0    ┆ 0    ┆ 3.833 ┆ null           │
│ Salsas   ┆ Salsa verde          ┆ 100     ┆ 38   ┆ … ┆ 0    ┆ 0    ┆ 0.6   ┆ null           │
└──────────┴──────────────────────┴─────────┴──────┴───┴──────┴──────┴───────┴────────────────┘

In [175]:
ultim[168:178]

shape: (10, 10)
┌───────────────────┬─────────────┬─────────┬──────┬───┬──────┬──────┬────────┬────────────────┐
│ Grupo de alimento ┆ Alimento    ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA ┆ SAT  ┆ SODIO  ┆ AZUCAR AÑADIDA │
│ ---               ┆ ---         ┆ ---     ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---    ┆ ---            │
│ str               ┆ str         ┆ i64     ┆ i64  ┆   ┆ str  ┆ str  ┆ str    ┆ str            │
╞═══════════════════╪═════════════╪═════════╪══════╪═══╪══════╪══════╪════════╪════════════════╡
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 34   ┆ … ┆ 0    ┆ 0    ┆ 0.012  ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 0    ┆ … ┆ s/i  ┆ s/i  ┆ s/i    ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 42   ┆ … ┆ 0    ┆ 0    ┆ 0.003  ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 43   ┆ … ┆ 0    ┆ 0    ┆ 0.039  ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 41   ┆ … ┆ 0    ┆ 0    ┆ 0.01   ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 48   ┆ … ┆ 0    ┆ 0    ┆ 0.012  ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 40   ┆ … ┆ 0    ┆ 0    ┆ 0.009  ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 1    ┆ … ┆ s/i  ┆ s/i  ┆ 0.0089 ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 32   ┆ … ┆ 0.03 ┆ 0.01 ┆ 0.042  ┆ null           │
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 24   ┆ … ┆ 0    ┆ 0    ┆ 0.049  ┆ null           │
└───────────────────┴─────────────┴─────────┴──────┴───┴──────┴──────┴────────┴────────────────┘

In [176]:
ultim[168+5]

shape: (1, 10)
┌───────────────────┬─────────────┬─────────┬──────┬───┬──────┬─────┬───────┬────────────────┐
│ Grupo de alimento ┆ Alimento    ┆ Gramaje ┆ KCAL ┆ … ┆ PUFA ┆ SAT ┆ SODIO ┆ AZUCAR AÑADIDA │
│ ---               ┆ ---         ┆ ---     ┆ ---  ┆   ┆ ---  ┆ --- ┆ ---   ┆ ---            │
│ str               ┆ str         ┆ i64     ┆ i64  ┆   ┆ str  ┆ str ┆ str   ┆ str            │
╞═══════════════════╪═════════════╪═════════╪══════╪═══╪══════╪═════╪═══════╪════════════════╡
│ Bebidas           ┆ Agua tónica ┆ 100     ┆ 48   ┆ … ┆ 0    ┆ 0   ┆ 0.012 ┆ null           │
└───────────────────┴─────────────┴─────────┴──────┴───┴──────┴─────┴───────┴────────────────┘